
[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.21" }
teamcity-environments = { id = "io.github.rodm.teamcity-environments", version = "1.5.6" }
sonarqube = { id = "org.sonarqube", version = "7.1.0.6387" }

[libraries]
teamcity-configs-dsl-plugins = { module = "org.jetbrains.teamcity:configs-dsl-kotlin-plugins-latest", version = "1.0-SNAPSHOT" }
teamcity-server-api = { module = "org.jetbrains.teamcity:server-api", version = "2025.07" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version = "6.0.1" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
